### ISSUE TITLE
Why not use directly config.vm.synced_folder ENV['GOPATH'], "ENV["HOME"] + "/go" ?

### ISSUE THREAD

**Issue by billmetangmo** [brancz/vagrant-golang#1]
Hello,

Thanks for sharing the file.
I just wonder why you don't directly do :   
`config.vm.synced_folder ENV['GOPATH'], ENV["HOME"] + "/go"
because the result seems to be the same.

**Comment by brancz** [comment]
That would work as well, do you want to open a PR? :)

**Comment by billmetangmo** [comment]
Of course @brancz . I have opened it :).

**Comment by brancz** [comment]
closing via #2, thanks a lot @billmetangmo !
